### PR TITLE
 Added a few covers for Japanese Exclusive Games and added 1:1 Square Versions for Incorrectly Sized Covers Submitted by t0ma70

### PR DESCRIPTION
**Pull request by aaaaafuck**

### CODE REVIEW

**Comment by aaaaafuck** [comment]
I can't find what game Jah Mong from my console is on the catalog I put the cover there anyways I'll try and find the id when I have the time. Also the catalog file uses the character * so any games with that are named incorrectly. This should be 98-99% of the japanese exclusive games.

**Comment by mrneo240** [comment]
Sounds good. I have a computer again. 

Thank you!

**Comment by aaaaafuck** [comment]
> Sounds good. I have a computer again.
> 
> Thank you!

Happy to have you back! Hope everything is good with you.

I don't know why it failed if you need me to change anything let me know.

**Comment by mrneo240** [comment]
I think it's an issue with github actions changes.

**Pull request merged**
